### ISSUE TITLE
Ace 3 G-Force research.

### ISSUE THREAD

**Issue by blackwatchint** [blackwatchint/blackwatchint#53] opened 2015-11-08 14:56 UTC
Find any materials regarding the realism of the G-Force; Ways of tweaking it, disabling, how it works and so on.

**Comment by adios113** [comment] 2015-11-08 15:03
Aparrently, playing as a "Pilot Class" from the editor, significantly reduces the G-Forces effects.

**Comment by Fourjays** [comment] 2015-11-25 11:35
I've checked and can't find any difference between spawning pilot units or using specific uniforms, vests, or helmets.

An option I came across was the ability to edit the G-Force coefficient on units. This example would turn it off, but I've confirmed that values between 0 and 1 can adjust the point of G-LOC:
```sqf
pilot setVariable ["ACE_GForceCoef", 0];
```

@adios113 Is there a way to define a unit as a "pilot" in SQF? Wondering if we're missing some obvious configuration option here.

**Comment by adios113** [comment] 2015-11-25 17:20
Yes, of course. There is an option to name a unit and then call the specific unit in a script.
Should be no problem implementing it. We just have to figure out the specific value we want to use.

**Comment by Fourjays** [comment] 2015-11-26 10:36
I meant if there was a "pilot" class in ACE the same way there is medical/engineer? The current G-LOC point seem consistent with the values for an untrained, unequipped pilot. So I wonder if we're missing some ACE config option, script line or feature that would define a player as being a pilot and therefore capable of a higher G-LOC point.

The option I posted is very sensitive (adjusting to 0.5 practically turns it off), so we're probably looking at something around 0.7 to 0.9.

**Comment by Fourjays** [comment] 2015-12-12 12:32
This is from the AGM Wiki, but we already know (and it does appear to be the case here) that a lot of ACE features have been taken from AGM.

https://github.com/KoffeinFlummi/AGM/wiki/For-Mission-Makers#23-defining-a-unit-as-a-pilot

Looks like default pilot units are "defined" as pilots by using this coefficient value and setting it to 0.75. I'll try to test it tonight and see how it feels, but I think we'll probably be going ahead with setting that value on our fixed-wing pilot roles.

**Comment by Fourjays** [comment] 2015-12-13 10:35
Tested and created an action item with #142. Closing as research concluded.

**Closed by Fourjays** 2015-12-13 10:35 UTC
Labels: Research
