### ISSUE TITLE
Werthless HC Script error

### ISSUE THREAD

**Issue by ShiFoo** [blackwatchint/blackwatchint#192] opened 2015-12-21 16:07 UTC
I got this error while playing Ryans Coffee Patrol:

http://steamcommunity.com/sharedfiles/filedetails/?id=580573306

I wonder why i got this error, because the script should execute on my machine when i join (init.sqf). This, although, popped up in the middle of the op. maybe when the HCs connected... It could potentially point out a problem with the script or why the HCs didnt work from the beginning.

**Comment by Fourjays** [comment] 2015-12-21 20:34
They weren't connected at the start of the mission, I had to reconnect them while the mission was being made.

This error is probably related to the debug not being available for IND though. The HCs seem to disconnect when script errors occur (including one caused by an HLC AK).

**Comment by Fourjays** [comment] 2015-12-22 10:07
Need to test and determine if the error is map or faction specific. Should be done with vanilla equipment at spawn to rule out issues caused by modpack gear.

**Comment by ShiFoo** [comment] 2015-12-28 09:19
I am under the impression that it is hardly reproducable because it has something to do with multiple HC instances. Almost every mission since did not have this error....  Maybe we can close this until it pops up again and the HCs look fine...

**Comment by Fourjays** [comment] 2015-12-28 10:21
Still needs testing to determine if this error (or others) occur when playing Zeus as OPFOR or IND (as was the case when this error occurred).

**Comment by ShiFoo** [comment] 2015-12-28 12:28
I was just on the server and tried it as independent and opfor zeus. Everything was working fine. I had the WHK toggle debug, spawned units were transferred to the HCs correctly, etc.

Not able to reproduce the problem.

**Comment by Fourjays** [comment] 2015-12-28 13:32
I'll close this for now. Will reopen if it occurs again.

**Closed by Fourjays** 2015-12-28 13:32 UTC
Labels: Medium Priority, Pending, Template
