### ISSUE TITLE
Chinook Minigun deafness problem

### ISSUE THREAD

**Issue by blackwatchint** [blackwatchint/blackwatchint#51] opened 2015-11-06 22:53 UTC
Chinook's Minigun is making everyone deaf, no matther if the earplugs are in or not.

**Comment by Fourjays** [comment] 2015-11-07 10:08
Is it possible this is by design? Myself, Ryan and others had a similar experience in iFu's mission where the .50 cal Humvees used were making us deaf with earplugs in.

**Comment by adios113** [comment] 2015-11-07 12:58
I know the bug with the .50 cal on ground vehicles, where it will make you deaf even if you have earplugs in. The thing with it is, that it will happen only if you put the earplugs in inside the vehicle, while you already are getting deaf. You have to make sure the deafness dissapears, then put the plugs in.

**Comment by DawkTux** [comment] 2015-11-23 20:31
It would be good to know which Chinook model is causing this, since there are a few.

**Comment by ShiFoo** [comment] 2015-11-23 22:41
My hypothesis: Earplugs need to be inserted BEFORE actually starting to get deaf. Otherwise it will not work. I guess this issue is not related to the/a chinook.

**Comment by Fourjays** [comment] 2015-11-24 10:42
I think it is likely that it isn't related to the Chinook and that it is a different issue, but lets test to be sure.

RHS has multiple CH-47 Chinooks (e.g. US Army (W) > Helicopters), but they are just texture variations to my knowledge.

**Comment by abelarno** [comment] 2016-01-09 13:44
When gunning the chinook, you need to have the earplugs inserted before starting to fire. If you don't, and insert the earplugs after the first few rounds, you'll still do deaf. Having earplugs in makes you don't go deaf.

When you are outside the helicopter, near the guns, earplugs don't matter. Even if you inserted them before the guns fire, you'll still go deaf like you don't have them in.

This is with the RHS chinook, standing next to the vanilla chinook with earplugs in does not seem to cause deafness. Checking with ace devs if they know where the issue lies.

**Comment by Fourjays** [comment] 2016-02-03 12:41
Closing as it is an intended feature and not a bug.

**Closed by Fourjays** 2016-02-03 12:41 UTC
Labels: Intended, Modpack
